### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by Phantum** [AndrolGenhald/Factorio-Boxing-2#1]
So there seems to be no way to support Angels, and if you have angels in your game, this mod can't recognize the bob's ores without some finagling.

Also the moment you research the first Tech, aka wooden boxing, you lose the ability to handcraft anything due to the recursive nature of this mod.   To fix this I changed all of the categories in recipes to crafting-with-fluids which means you can no longer hand craft the boxes, but you'll at least be able to handcraft anything else.

How do you generate the new icons so that I can have Angel's ores/bob's ores icons back into my game?

**Comment by AndrolGenhald** [comment]
1. The issue with handcrafting has been noted in Bob's mods with synthetic wood as well (though not to this degree), it's not possible for a mod to fix, the way recipes work will likely have to be significantly changed in the base game. When I was playing I preferred to automate crafting, but I liked to use wooden boxes for carrying rails and concrete, if you don't like that trade-off the easiest fix is to comment out line 21 of prototypes/recipes/categories.lua where boxing-wooden is added to handcrafting. I'll probably start playing again with 0.15, and iirc they're adding mod options, so I'll probably end up adding it as an option in the game then.

2. For Angels support, when I looked into it before I didn't know all of the interactions with other mods and I wasn't playing as much by that time. If you want to try adding it yourself I'd be happy to accept a pull request. Subgroups and specific items can be added in config.lua. Icon generation is a bit of a hack, you have to set boxing.generateIconConfig = true; at the end of config.lua, then launch the game and open a new map (loading an old one may or may not work, I don't remember). The mod will look at all the items it needs icons for and write it out to a file, then you'll have to run generate_icons.py to actually generate the boxing icons (using Python, obviously, and PIL). I wrote the script for my linux install, if you're running windows you'll probably have to mess with some of the filepaths.
