### ISSUE TITLE
Error in assignID: item-subgroup with name 'boxing-wooden-train-transport' does not exist.

### ISSUE THREAD

**Issue by digital-pet** [AndrolGenhald/Factorio-Boxing-2#3]
I am getting this error when trying to load boxing in a fresh 1.0 install.

Failed to load mods: Error in assignID: item-subgroup with name 'boxing-wooden-train-transport' does not exist.

Source: wooden-box-of-rail (item).

Mods to be disabled:
• boxing-2 (2.18.0)

![image](https://user-images.githubusercontent.com/47679051/90298478-776bc680-de60-11ea-827b-995aa8a30706.png)

**Comment by AndrolGenhald** [comment]
Fixed with 2.18.1. Rails are a bit special and there's some hard-coded stuff for them. Now the subgroup name for rails is grabbed from the rail item rather than being hard-coded.
